# Generated by Django 5.2.17 on 2026-10-06 01:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=180)),
                ('address', models.CharField(blank=True, max_length=250)),
                ('flyer_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicado'), ('archived', 'Archivado')], default='draft', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('event_date',),
            },
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('kind', models.CharField(choices=[('percent', 'Porcentaje'), ('fixed', 'Importe fijo')], max_length=8)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('uses', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='tickets.event')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('buyer_name', models.CharField(max_length=160)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Aprobado'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', max_length=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='ARS', max_length=3)),
                ('payment_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('preference_id', models.CharField(blank=True, max_length=100)),
                ('qr_token', models.TextField(blank=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('discount_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.discountcode')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tickets.event')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TicketDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='tickets.order')),
            ],
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('sale_starts_at', models.DateTimeField(blank=True, null=True)),
                ('sale_ends_at', models.DateTimeField(blank=True, null=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='tickets.event')),
            ],
            options={
                'ordering': ('display_order', 'price'),
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('reserved_order', models.UUIDField(blank=True, db_index=True, null=True)),
                ('reserved_until', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='tickets.event')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='tickets.tickettype')),
            ],
            options={
                'ordering': ('label',),
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tickets.order')),
                ('seat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tickets.seat')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.tickettype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='discountcode',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='unique_event_discount_code'),
        ),
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('event', 'label'), name='unique_event_seat'),
        ),
    ]
