# Generated by Django 5.2.17 on 2026-10-06 01:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_orderline_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checked_in_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qr_token',
        ),
        migrations.CreateModel(
            name='IssuedTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qr_token', models.TextField(unique=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_tickets', to='tickets.orderline')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
