# Generated by Django 5.2.17 on 2026-10-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_discountcode_value_alter_tickettype_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer_dni',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_phone_area_code',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_phone_number',
            field=models.CharField(default='', max_length=12),
        ),
    ]
